### PR TITLE
Merge for 7.1.4 CP release

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for other issues
- [x] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by luck3y** [comment]
@maschmid @ruromero FYI

@apintea @rgdoliveira  As a reminder, we need to make sure that when CP releases are done we merge the changes into the release branch.

**Review by rgdoliveira — DISMISSED** [review]
Looks good to me.

**Comment by luck3y** [comment]
Updated for conflicts @rgdoliveira can you reapprove?

**Review by rgdoliveira — DISMISSED** [review]

**Comment by luck3y** [comment]
@rgdoliveira Sorry, last review time, I'll merge it as soon as you approve!

**Review by apintea — APPROVED** [review]

**Pull request merged**
