### PR TITLE
Update to EAP 7.0.9.CP.CR1

### PR DESCRIPTION
**Pull request by dosoudil**
This PR rollbacks the application of one-off patch for 7.0.8, and then does the upgrade to next CP release - 7.0.9.

### CODE REVIEW

**Review by goldmann — APPROVED** [review]

**Comment by goldmann** [comment]
Can you please squash these two commits and provide better commit message?

**Review by goldmann — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by dosoudil** [comment]
I fixed the title of PR and the commit with the upgrade to next CP. The first commit is the proper revert of previous commit in the branch related to one-off patch. In the logical way, it doesn't make sense to squash/meld them together because of common usage of git - use git revert command to rollback a change which was merged before. One-off patches are blind branches in the context of product lifecycle.

**Comment by goldmann** [comment]
Sure, now it makes sense, the commit title mentions the correct version, merging.

**Review by goldmann — APPROVED** [review]

**Pull request merged**
