### PR TITLE
[CLOUD-2694] Create a dev branch for EAP on OpenShift 7.2.0.Beta work

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.jboss.org/browse/CLOUD-2694

Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>

This is to get the existing, very early but now way out of date, eap72-dev branch in a state where we can do standalone image dev work for the beta image of EAP on OpenShift 7.2.0.

There are 3 basic parts to the commit history here:

1) Everything up to the "Merge branch 'eap-cd-dev' into eap72-dev" commit is getting the old branch abandoned since January to the same state as the eap-cd-dev branch as of the release of EAP CD 13.  Our intent is EAP on OS 7.2 is going to largely track EAP CD, so the starting point for work going forward is EAP CD 13.

2) Next a few commits converting the branch content from CD to EAP on OS. Name and other metadata changes, text changes, appropriate installer module, etc.

3) Last commit brings in the latest test build zip of EAP 7.2.0.Beta.

### CODE REVIEW

**Review by luck3y — DISMISSED** [review]
lgtm, the diff is quite a bit smaller than the log ;)

**Comment by bstansberry** [comment]
Haha, yeah!  Looking at the diff it seems I took a long road to a nearby destination!

**Comment by bstansberry** [comment]
@tremes @maschmid A test build of this image is at docker pull docker-registry.engineering.redhat.com/bstansbe/eap72-beta:CLOUD-2694

My goal with this PR was to take CD 13 and convert to the appropriate metadata, file names, text etc for the EAP 7.2 Beta image. Plus add in the correct zip. That would bring this branch to the correct state for final dev work on the beta image, which, if it's ok with you guys I'd like to do in separate PRs after this gets merged.

If you prefer I can continue pushing to this branch.

I'm doing an analysis of this branch (and the -openshift-image branch and jboss-eap-modules) to look for anything that's different vs 7.1 that is not appropriate for EAP on OpenShift 7.2. (Don't expect much.) And I'll audit for anything that's gone into eap-cd-dev since CD 13 that needs porting to here. That's the extent of expected additional work on this branch before it would be ready for the real 7.2 Beta build.

@luck3y FYI. (This isn't news to you. ;) ). Also the PR has changed a bit since you approved. Last two commits.

**Review by luck3y — DISMISSED** [review]

**Comment by bstansberry** [comment]
I updated this with the CR2 artifact.

**Review by luck3y — DISMISSED** [review]

**Review by luck3y — DISMISSED** [review]

**Comment by tremes** [comment]
@bstansberry  I am sorry I somehow missed this one. Yes makes sense. I am mainly interested in the image and the templates.

**Comment by bstansberry** [comment]
@tremes @maschmid @luck3y I updated this PR per Ken's comment on https://github.com/jboss-container-images/jboss-eap-7-openshift-image/pull/108 re using --build-tech-preview instead of hard coding it in image.yaml.  Here I updated the last commit.  I also rebuilt and pushed the test images.

**Review by luck3y — APPROVED** [review]

**Pull request merged**
