### PR TITLE
Update module.yaml

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by spolti** [comment]
@ettoreleandrotognoli  @luck3y can you please take a look?

**Comment by spolti** [comment]
probably a new tag will be required.

**Review by ettoreleandrotognoli — APPROVED** [review]

**Review by luck3y — APPROVED** [review]

**Comment by luck3y** [comment]
@spolti thanks!

**Comment by luck3y** [comment]
@spolti EAP_LP_746_CR1

**Comment by spolti** [comment]
Thanks @luck3y

**Pull request merged**
